[package]
name = "cooltraption_runtime_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cooltraption_runtime = { path = "../cooltraption_runtime" }
